namespace VoidChase.MovingObjects
{
	public enum MovingObjectType
	{
		MEDIUM_ASTEROIDS_1,
		MEDIUM_ASTEROIDS_2,
		DEFAULT_PROJECTILES,
		SINGLE_PROJECTILES_WEAPON_SWITCHERS,
		TRIPLE_PROJECTILES_WEAPON_SWITCHERS,
		TRIPLE_SPREAD_PROJECTILES_WEAPON_SWITCHERS
	}
}