namespace VoidChase.MovingObjects
{
	public enum MovingObjectType
	{
		GREEN_SMALL_ASTEROID,
		GREEN_FAST_ASTEROID,
		COLORFUL_SMALL_ASTEROID,
		COLORFUL_FAST_ASTEROID,
		COLORFUL_BIG_ASTEROID,
		BLACK_SMALL_ASTEROID,
		BLACK_FAST_ASTEROID
	}
}